name: examen_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  backdrop: ^0.7.1
  http: ^0.13.4
  bloc: ^8.0.3
  feature_discovery: ^0.14.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
